apiVersion: v1
kind: Namespace
metadata:
  name: user1
---
apiVersion: v1
kind: Namespace
metadata:
  name: user2
---
apiVersion: v1
kind: Namespace
metadata:
  name: user3

#! export registry creds to all namespaces
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry1-creds
  namespace: user1
spec:
  toNamespaces:
    - user2
    - user3
---
apiVersion: v1
kind: Secret
metadata:
  name: registry1-creds
  namespace: user1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTEiOnsiYXV0aCI6ImRYTmxjakU2Y0dGemN6RT0iLCJwYXNzd29yZCI6InBhc3MxIiwidXNlcm5hbWUiOiJ1c2VyMSJ9fX0=
