#@data/values
---
google_analytics: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-175777013-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-175777013-1');

    const sendGoogleAnalyticsEvent = (action, category, label, value) => {
      const eventBody = {
        'event_category' : category,
        'event_label' : label,
        'value' : value
      }
      gtag('event', action, eventBody);
    }
  </script>
