---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-app-sa
  namespace: kctrl-tutorial
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-app-role
  namespace: kctrl-tutorial
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
  namespace: kctrl-tutorial
subjects:
- kind: ServiceAccount
  name: simple-app-sa
  namespace: kctrl-tutorial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-app-role
